from typing import List, Optional

from sqlalchemy import ForeignKey, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db import Base

class Unit(Base):
    """
    Unit model representing a single learning module within a Level.

    Each Unit contains the reference to an SCORM package or digital resource.
    Units are the bridge between the academic structure (Levels) and the 
    tracking system (ScormProgress).
    """

    __tablename__ = "units"

    unit_id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    title: Mapped[str] = mapped_column(String(200), nullable=False)
    description: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # scorm_url: The path or identifier for the SCORM package to be loaded
    scorm_url: Mapped[str] = mapped_column(String(500), nullable=False)

    # Foreign Key: Each unit belongs to exactly one level
    level_id: Mapped[int] = mapped_column(ForeignKey("levels.level_id"), nullable=False)

    # Relationships
    # Link back to the Level this unit belongs to
    level: Mapped["Level"] = relationship(back_populates="units")

    # Link to all progress records generated by students for this specific unit
    progress_records: Mapped[List["ScormProgress"]] = relationship(back_populates="unit")
