"""init core tables

Revision ID: f93d4cdc2ac3
Revises:
Create Date: 2026-04-28 14:36:30.557385

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f93d4cdc2ac3"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("user_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("recovery_email", sa.String(), nullable=True),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "SUPER_ADMIN",
                "ADMIN",
                "STUDENT",
                "PROFESSOR",
                name="userrole",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("recovery_email"),
    )
    op.create_table(
        "courses",
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("course_name", sa.String(), nullable=False),
        sa.Column("course_description", sa.String(length=2000), nullable=False),
        sa.Column("course_price", sa.Float(), nullable=False),
        sa.Column("course_duration", sa.Integer(), nullable=False),
        sa.Column("course_tags", sa.JSON(), nullable=False),
        sa.Column("instructor_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["instructor_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("course_id"),
    )
    op.create_table(
        "enrollments",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("enrollment_date", sa.DateTime(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.course_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "course_id"),
    )
    op.create_table(
        "modules",
        sa.Column("module_id", sa.Integer(), nullable=False),
        sa.Column("module_name", sa.String(), nullable=False),
        sa.Column("module_description", sa.String(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.course_id"],
        ),
        sa.PrimaryKeyConstraint("module_id"),
    )
    op.create_table(
        "sections",
        sa.Column("section_id", sa.Integer(), nullable=False),
        sa.Column("section_name", sa.String(), nullable=False),
        sa.Column("section_description", sa.String(), nullable=False),
        sa.Column("section_order", sa.Integer(), nullable=False),
        sa.Column("module_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["module_id"],
            ["modules.module_id"],
        ),
        sa.PrimaryKeyConstraint("section_id"),
    )
    op.create_table(
        "lessons",
        sa.Column("lesson_id", sa.Integer(), nullable=False),
        sa.Column("lesson_name", sa.String(), nullable=False),
        sa.Column("section_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["sections.section_id"],
        ),
        sa.PrimaryKeyConstraint("lesson_id"),
    )
    op.create_table(
        "progress",
        sa.Column("progress_id", sa.Integer(), nullable=False),
        sa.Column("progress_percentage", sa.Float(), nullable=False),
        sa.Column(
            "progress_status",
            sa.Enum("NOT_STARTED", "IN_PROGRESS", "COMPLETED", name="progressstatus"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("lesson_id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.course_id"],
        ),
        sa.ForeignKeyConstraint(
            ["lesson_id"],
            ["lessons.lesson_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("progress_id"),
    )
    op.drop_table("dummytable")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dummytable",
        sa.Column("dummyfield", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("dummyfield", name=op.f("dummytable_pkey")),
    )
    op.drop_table("progress")
    op.drop_table("lessons")
    op.drop_table("sections")
    op.drop_table("modules")
    op.drop_table("enrollments")
    op.drop_table("courses")
    op.drop_table("users")
    # ### end Alembic commands ###
